### ISSUE TITLE
Bottom Knob causes amp distortion

### ISSUE THREAD

**Issue by thatdoggo** [TheRealCodeCube/AtomSynth#4]
I noticed that when messing around with the bottom knob the output is either completely frozen, or chopped up

**Comment by thatdoggo** [comment]
[[[0.000000:[[-1.000000:-1.000000:][-1.000000:-1.000000:][-1.000000:-1.000000:][-1.000000:-1.000000:][-1.000000:-1.000000:][-1.000000:-1.000000:][-1.000000:-1.000000:][-1.000000:-1.000000:][-1.000000:-1.000000:][-1.000000:-1.000000:]][[230.000000:64.000000:][0.000000:]]][12.000000:[[0.000000:1.000000:][-1.000000:-1.000000:][-1.000000:-1.000000:][-1.000000:-1.000000:][-1.000000:-1.000000:][-1.000000:-1.000000:][-1.000000:-1.000000:][-1.000000:-1.000000:][-1.000000:-1.000000:][-1.000000:-1.000000:][-1.000000:-1.000000:]][[253.000000:248.000000:][1.000000:[1.255345:1.000000:][0.000000:2.000000:][6.806314:2.000000:][1.518446:1.210467:][0.000000:1.140000:][1.000000:0.000000:0.000000:1.000000:s:[-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:]][1.000000:0.000000:0.000000:1.000000:s:[-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:]][0.420000:0.000000:-1.000000:1.000000:s:[-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:]][1.000000:0.000000:0.000000:1.000000:s:[-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:]][0.265000:0.000000:-1.000000:1.000000:s:[-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:]][0.065000:0.000000:-1.000000:1.000000:s:[-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:]][1.000000:0.000000:0.000000:1.000000:s:[-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:]][1.000000:0.000000:0.000000:1.000000:s:[-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:]][1.000000:0.000000:0.000000:1.000000:s:[-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:]][1.000000:0.000000:0.000000:1.000000:s:[-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:]][1.000000:0.000000:0.000000:1.000000:s:[-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:]]]]][10.000000:[[0.000000:0.000000:][1.000000:0.000000:][-1.000000:-1.000000:][-1.000000:-1.000000:][-1.000000:-1.000000:][-1.000000:-1.000000:][-1.000000:-1.000000:][-1.000000:-1.000000:][-1.000000:-1.000000:][-1.000000:-1.000000:][-1.000000:-1.000000:]][[158.000000:381.000000:][2.000000:[1.000000:][1.000000:0.000000:-1.000000:1.000000:s:[-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:]][5.730000:][-0.510000:2.000000:-1.000000:1.000000:s:[1.000000:0.000000:1.000000:][1.000000:0.076471:0.682353:][5.000000:0.000000:1.000000:][1.000000:0.000000:0.352941:]][0.000000:0.000000:-1.000000:1.000000:s:[-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:]][0.990000:0.000000:-1.000000:1.000000:s:[-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:]][1.000000:0.000000:0.000000:1.000000:s:[0.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:0.847059:]][1.000000:0.000000:-1.000000:1.000000:s:[-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:]][0.000000:0.000000:-1.000000:1.000000:s:[-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:]][0.500000:0.000000:-1.000000:1.000000:s:[-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:]][1.000000:0.000000:0.000000:1.000000:s:[-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:]][0.000000:0.000000:-4.000000:4.000000:so:[-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:]][-24.000000:0.000000:-100.000000:100.000000:sc:[-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:]][4.000000:0.000000:-100.000000:100.000000:sc:[-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:]][0.000000:0.000000:-12.000000:12.000000:ss:[-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:]][-2.000000:0.000000:-2.000000:2.000000:s:[-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:][-1.000000:0.000000:1.000000:]]]]][1.000000:[[2.000000:0.000000:][-1.000000:-1.000000:][-1.000000:-1.000000:][-1.000000:-1.000000:][-1.000000:-1.000000:][-1.000000:-1.000000:][-1.000000:-1.000000:][-1.000000:-1.000000:][-1.000000:-1.000000:][-1.000000:-1.000000:][-1.000000:-1.000000:]][[233.000000:563.000000:][1.000000:]]]][sTestPatch1:]]

This is the patch im trying to use

**Comment by TheRealCodeCube** [comment]
I think I know what the problem is. The VST detects notes being 'off' by looking at the output and, if it is very close to 0, it thinks the note is finished. When moving the bottom knob to a higher value, the output becomes a flat line, but is no longer zero.

To fix this, I will change the note end detection to look for flat lines instead of just zero.

**Comment by TheRealCodeCube** [comment]
I tested out your patch, and it looks like there is more of a problem than just the one I mentioned above, as certain functions seems to be broken inside the Basic Osc, even when I set it back to default values.
