### ISSUE TITLE
Strange problems on a particular system.

### ISSUE THREAD

**Issue by TheRealCodeCube** [TheRealCodeCube/AtomSynth#7]
(From reddit)
The original description of the issue can be found [here](https://www.reddit.com/r/edmproduction/comments/6tc5dj/im_making_a_free_modular_synthesis_vst_want_to/dljuhrs/). When loading the default patch, the left channel works fine, but the right channel maxes out.

**Comment by temrix** [comment]
The same happens in Ardour4. I don’t recommend to reproduce it with speakers on because it is pretty loud although the volume was turned down.

**Comment by temrix** [comment]
I tried it now with a new debug build. I have set the audio level really low. From what I remember, it could be that I really heard the sound that it is supposed to make but it grew exponentially louder on the left channel but maybe also on the right.

I have to set a limiter next time!
