### ISSUE TITLE
include-file not found during compilation

### ISSUE THREAD

**Issue by temrix** [TheRealCodeCube/AtomSynth#9]
```
In file included from ../../Source/Adsp/Fir.cpp:8:0:
../../Source/Adsp/Fir.h:13:35: fatal error: Technical/AudioBuffer.h: File or folder not found
 #include "Technical/AudioBuffer.h"
```

It cannot find the correct files because the path is wrong. It should be instead:
`#include "../Technical/AudioBuffer.h"`

This is because the compiler goes to the file that is going to be compiled, this file has an `#include` and the current working directory has changed. In other words, the path of the `#include` should be relative to the current working directory.

I don’t know if Windows can handle this the same way. The JUCE library compiles on all platforms, so we should look into how they have done it.

**Comment by TheRealCodeCube** [comment]
The latest commit should fix that. I changed the header search paths on Linux to be relative to the project. You will need to load and save the project in projucer for the changes to take effect.

**Comment by TheRealCodeCube** [comment]
I had previously set the source folder as a place to search for includes, but it was using an absolute path.

**Comment by temrix** [comment]
I think this can be closed now. No include errors anymore.
